//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OASIS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class authorized
    {
        public authorized()
        {
            this.check = new HashSet<check>();
            this.invoice = new HashSet<invoice>();
            this.personel = new HashSet<personel>();
        }
    
        public int authorizedid { get; set; }
        public int companyget { get; set; }
        public int regionget { get; set; }
        public int unitget { get; set; }
        public int departmanget { get; set; }
        public virtual HttpPostedFileBase profilephotoFile { get; set; }
        public string profilephoto { get; set; }
        public virtual HttpPostedFileBase digitalcvFile { get; set; }
        public string digitalcv { get; set; }
        public string authorized1 { get; set; }
        public string tc { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string adres { get; set; }
        public string civilstatusget { get; set; }
        public string children { get; set; }
        [Display(Name = "Date Edit")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy.MM.dd}")]
        public System.DateTime? workingstart { get; set; }
        [Display(Name = "Date Edit")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy.MM.dd}")]
        public System.DateTime? workingstop { get; set; }
        public string performance { get; set; }
        public string pirim { get; set; }
        public string pay { get; set; }
        public string mesai { get; set; }
        public string mesaidays { get; set; }
        public string gender { get; set; }
    
        public virtual company company { get; set; }
        public virtual departman departman { get; set; }
        public virtual region region { get; set; }
        public virtual unit unit { get; set; }
        public virtual ICollection<check> check { get; set; }
        public virtual ICollection<invoice> invoice { get; set; }
        public virtual ICollection<personel> personel { get; set; }
    }
}
