//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OASIS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class comment
    {
        public int checkcommentid { get; set; }
        public string referancenumber { get; set; }
        public int companyget { get; set; }
        public int regionget { get; set; }
        public int unitget { get; set; }
        [Display(Name = "Date Edit")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy.MM.dd}")]
        public System.DateTime? date { get; set; }
        public string namesurname { get; set; }
        public string tc { get; set; }
        public string tel { get; set; }
        public string email { get; set; }
        public string subject { get; set; }
        public string comment1 { get; set; }
        public string color { get; set; }
    
        public virtual company company { get; set; }
        public virtual region region { get; set; }
        public virtual unit unit { get; set; }
    }
}
