//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OASIS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.authorized = new HashSet<authorized>();
            this.check = new HashSet<check>();
            this.comment = new HashSet<comment>();
            this.home = new HashSet<home>();
            this.invoice = new HashSet<invoice>();
            this.notice = new HashSet<notice>();
            this.personel = new HashSet<personel>();
            this.region = new HashSet<region>();
        }
    
        public int companyid { get; set; }
        public string company1 { get; set; }
    
        public virtual ICollection<authorized> authorized { get; set; }
        public virtual ICollection<check> check { get; set; }
        public virtual ICollection<comment> comment { get; set; }
        public virtual ICollection<home> home { get; set; }
        public virtual ICollection<invoice> invoice { get; set; }
        public virtual ICollection<notice> notice { get; set; }
        public virtual ICollection<personel> personel { get; set; }
        public virtual ICollection<region> region { get; set; }
    }
}
