//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OASIS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class departman
    {
        public departman()
        {
            this.authorized = new HashSet<authorized>();
            this.check = new HashSet<check>();
            this.home = new HashSet<home>();
            this.notice = new HashSet<notice>();
            this.personel = new HashSet<personel>();
        }
    
        public int departmanid { get; set; }
        public string departman1 { get; set; }
    
        public virtual ICollection<authorized> authorized { get; set; }
        public virtual ICollection<check> check { get; set; }
        public virtual ICollection<home> home { get; set; }
        public virtual ICollection<notice> notice { get; set; }
        public virtual ICollection<personel> personel { get; set; }
    }
}
