//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OASIS.Models.Entity
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
    
    public partial class invoice
    {
        public int invoiceid { get; set; }
        public int companyget { get; set; }
        public int regionget { get; set; }
        public int unitget { get; set; }
        public int authorizedget { get; set; }
        public int personelget { get; set; }
        public string referancenumber { get; set; }
        [Display(Name = "Date Edit")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy.MM.dd}")]
        public System.DateTime? date { get; set; }
        public string namesurname { get; set; }
        public string tc { get; set; }
        public string tel { get; set; }
        public string adres { get; set; }
        public string email { get; set; }
        public string product { get; set; }
        public string description { get; set; }
        public string subtotal { get; set; }
        public string tax { get; set; }
        public string total { get; set; }
        public string pay { get; set; }
    
        public virtual authorized authorized { get; set; }
        public virtual company company { get; set; }
        public virtual personel personel { get; set; }
        public virtual region region { get; set; }
        public virtual unit unit { get; set; }
    }
}
