//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OASIS.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class oasisEntities : DbContext
    {
        public oasisEntities()
            : base("name=oasisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<authorized> authorized { get; set; }
        public virtual DbSet<check> check { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<departman> departman { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<home> home { get; set; }
        public virtual DbSet<invoice> invoice { get; set; }
        public virtual DbSet<messagebox> messagebox { get; set; }
        public virtual DbSet<notice> notice { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<process> process { get; set; }
        public virtual DbSet<region> region { get; set; }
        public virtual DbSet<ucretbordro> ucretbordro { get; set; }
        public virtual DbSet<unit> unit { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<yuklenenbelgeler> yuklenenbelgeler { get; set; }
    }
}
