//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OASIS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class process
    {
        public process()
        {
            this.home = new HashSet<home>();
            this.notice = new HashSet<notice>();
        }
    
        public int processid { get; set; }
        public string process1 { get; set; }
    
        public virtual ICollection<home> home { get; set; }
        public virtual ICollection<notice> notice { get; set; }
    }
}
