//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OASIS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ucretbordro
    {
        public int ucretbordroid { get; set; }
        public double sgksabiti { get; set; }
        public double sgkisveren { get; set; }
        public double isverenissizsigfon { get; set; }
        public double isverenmaliyet { get; set; }
        public double nrkazanc { get; set; }
        public double iszsigiscipayi { get; set; }
        public double sgkiscipayi { get; set; }
        public double gvmahtari { get; set; }
        public double gelirvergisi { get; set; }
        public double agi { get; set; }
        public double kendiagiyuzdesi { get; set; }
        public double esagiyuzdesi { get; set; }
        public double birveikicocukagiyuzdesi { get; set; }
        public double uccocukyuzdesi { get; set; }
        public double dortveuzericocukyuzdesi { get; set; }
        public double damgavergi { get; set; }
        public double netkazanc { get; set; }
        public double gunlukkazanc { get; set; }
        public double pirimyuzdesi { get; set; }
        public double mesaiucreti { get; set; }
        public double yoneticifark { get; set; }
        public double yoneticipirimyuzdesi { get; set; }
        public double yoneticimesaiucreti { get; set; }
        public double pirimlimit { get; set; }
    }
}
