//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OASIS.Models.Entity
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class yuklenenbelgeler
    {
        public int belgeid { get; set; }
		public virtual HttpPostedFileBase belgeFile { get; set; }
        public string belge { get; set; }
		[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy.MM.dd}")]
        public System.DateTime? date { get; set; }
        public string Description { get; set; }
    
    }
}
